In [1]:
# import all libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler, LabelEncoder


In [2]:
#load data set
df=sns.load_dataset('tips')
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
#seperate the feature X and target/labels y
X=df[['total_bill']] #X always should be 2D array beceause of multiple features 
y=df['tip']


In [5]:
#train test split data  
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [18]:
#preprocess the data
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [19]:
#build the model 
model = LinearRegression()# call the model
model.fit(X_train, y_train) #train the model

LinearRegression()

In [8]:
#prediction
y_pred=model.predict(X_test) 

In [9]:
y_pred

array([3.27990295, 1.82233367, 5.92728216, 2.22136801, 2.52142515,
       2.2036563 , 3.57162517, 3.0006831 , 2.23595412, 4.0185853 ,
       2.47766682, 2.39952694, 3.33928926, 5.93770081, 2.36722912,
       2.18594459, 2.39431761, 2.60894182, 4.87499841, 5.09379008,
       3.70915137, 2.23803785, 2.47245749, 3.02256227, 2.55163924,
       2.29117297, 2.1619817 , 3.37575453, 4.48221527, 2.89649659,
       2.70687714, 4.86874722, 3.04339957, 3.08611604, 2.61727674,
       2.71208647, 2.62248607, 3.25177259, 3.41534541, 1.98486463,
       4.2842609 , 3.27052616, 2.60789996, 3.54349482, 2.93921306,
       3.87168232, 3.54245295, 2.44328527, 2.60581623])

In [10]:
y_test

78     3.00
6      2.00
156    5.00
236    1.00
193    2.02
118    1.80
54     4.34
65     3.15
201    2.01
155    5.14
32     3.00
109    4.00
181    5.65
59     6.73
110    3.00
133    2.00
122    2.50
93     4.30
112    4.00
95     4.73
7      3.12
209    2.23
69     2.09
60     3.21
22     2.23
213    2.50
97     1.50
3      3.31
141    6.70
130    1.50
152    2.74
56     3.00
106    4.06
186    3.50
203    2.50
115    3.50
66     2.47
91     3.50
35     3.60
16     1.67
47     6.00
241    2.00
36     2.00
5      4.71
55     3.51
192    2.56
73     5.00
74     2.20
17     3.71
Name: tip, dtype: float64

In [11]:
#we are going to predict for 10 but the answer is 12. which is wrong
model.predict([[10]])

array([12.04571446])

In [13]:
#now evaluation the model 
from sklearn.metrics import r2_score, mean_squared_error

#mean_squared_error
print('MSE:', mean_squared_error(y_test, y_pred))

#r2_score 
print('R2_score:', r2_score(y_test, y_pred))

MSE: 0.8791343556287315
R2_score: 0.5156242304586526


# save the model and load the model

In [15]:
#save the models
import pickle
pickle.dump(model, open('./save_models/model.pkl', 'wb')) #wb=write binary & pkl= pickle file


In [16]:
#load the model 
#rb=read binary will use to load the model
model_loaded=pickle.load(open('./save_models/model.pkl', 'rb')) 

In [17]:
model_loaded.predict([[10]])

array([12.04571446])