# Naïve Bayes algorithm
Naive Bayes is an algorithm for classification. It is based on Bayes theorem.
it is used for text classification.

 


In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#machine learning libraries
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
#load the data set from sklearn
from sklearn.datasets import load_iris

# Load the dataset
iris = load_iris()
#split the data set into X and y
X= iris.data
y= iris.target

#train test split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Gaussian Naive Bayes
Gaussian Naive Bayes is a probabilistic classifier that is used for binary classification. It is used when the features are continuous.

In [3]:
#Define the model
gnb = GaussianNB()

#fit the model
gnb.fit(X_train, y_train)

#predict
y_pred = gnb.predict(X_test)

#print and evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 1.0
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



# Multinomial Naive Bayes
Multinomial Naive Bayes is a probabilistic classifier that is used for multinomial classification. it is used when the features are categorical.

In [4]:
#now use the multinomial naive bayes
mnb = MultinomialNB()

#fit the model
mnb.fit(X_train, y_train)

#predict
y_pred = mnb.predict(X_test)

#print and evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))


Accuracy: 0.9
Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  3  8]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.75      1.00      0.86         9
           2       1.00      0.73      0.84        11

    accuracy                           0.90        30
   macro avg       0.92      0.91      0.90        30
weighted avg       0.93      0.90      0.90        30



# Bernoulli Naive Bayes
Bernoulli Naive Bayes is a probabilistic classifier that is used for binary classification. it is used when the features are binary.

In [5]:
#now use the bernoulli naive bayes
# Import the necessary libraries
from sklearn.naive_bayes import BernoulliNB

# Define the model
bnb = BernoulliNB()

# Fit the model
bnb.fit(X_train, y_train)

# Predict
y_pred = bnb.predict(X_test)

# Print and evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.3
Confusion Matrix:
 [[ 0 10  0]
 [ 0  9  0]
 [ 0 11  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00        10
           1       0.30      1.00      0.46         9
           2       0.00      0.00      0.00        11

    accuracy                           0.30        30
   macro avg       0.10      0.33      0.15        30
weighted avg       0.09      0.30      0.14        30



c:\Users\HP\miniconda3\envs\ml_python\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\HP\miniconda3\envs\ml_python\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\HP\miniconda3\envs\ml_python\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
